# Generated by Django 4.2.7 on 2023-12-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='key',
            new_name='file_path',
        ),
    ]
