# Generated by Django 4.2.7 on 2023-12-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_key_mymodel_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='file_path',
            new_name='object_path',
        ),
    ]
